/**
 * Generates the service worker after a Vite build.
 *
 * The precache list is read off the real `dist/` output rather than written by
 * hand, so it can never drift from Vite's content-hashed filenames, and the
 * cache name is derived from those filenames so a new build invalidates the old
 * cache automatically.
 *
 *   node scripts/build-sw.mjs [distDir]
 */
import { createHash } from 'node:crypto';
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, posix, relative, sep } from 'node:path';

const DIST = process.argv[2] ?? 'dist';

/** Files that would only bloat the cache, or that must always hit the network. */
const EXCLUDE = new Set(['sw.js', 'manifest.webmanifest']);
const EXCLUDE_EXT = new Set(['.map']);

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

const files = walk(DIST)
  .map((f) => relative(DIST, f).split(sep).join(posix.sep))
  .filter((f) => !EXCLUDE.has(f))
  .filter((f) => !EXCLUDE_EXT.has(f.slice(f.lastIndexOf('.'))))
  .sort();

if (files.length === 0) throw new Error(`no files found in ${DIST} — run the build first`);

// The manifest is fetched at install too, but is not part of the app shell.
const precache = ['./', ...files.map((f) => `./${f}`), './manifest.webmanifest'];
const version = createHash('sha256').update(precache.join('\n')).digest('hex').slice(0, 12);

const sw = `/* Generated by scripts/build-sw.mjs — do not edit. */
const CACHE = 'dodge-asteroid-${version}';
const PRECACHE = ${JSON.stringify(precache, null, 2)};

// Google Fonts is the one cross-origin dependency. Caching it at runtime is
// what lets an installed copy start with the right typeface while offline.
const FONT_HOSTS = ['https://fonts.googleapis.com', 'https://fonts.gstatic.com'];

// Static hosts commonly send \`Vary: Origin\` (GitHub Pages and \`vite preview\`
// both do). The worker precaches with its own fetch, which carries no Origin,
// while the page's module-script and stylesheet requests do — so a Vary-aware
// match misses every asset and the app fails to start offline despite being
// fully cached. These files are static and do not vary by origin.
const MATCH = { ignoreVary: true };

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      // addAll fails the whole install if any single request fails, so each
      // entry is added individually and a miss is tolerated.
      Promise.all(
        PRECACHE.map((url) =>
          cache.add(new Request(url, { cache: 'reload' })).catch(() => undefined),
        ),
      ),
    ),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  // The page asks for this explicitly, from a menu, so an update never
  // interrupts a run in progress.
  if (event.data === 'skip-waiting') self.skipWaiting();
});

function isFont(url) {
  return FONT_HOSTS.some((host) => url.startsWith(host));
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = request.url;

  if (isFont(url)) {
    // Stale-while-revalidate: instant from cache, refreshed in the background.
    event.respondWith(
      caches.open(CACHE).then(async (cache) => {
        const hit = await cache.match(request, MATCH);
        const network = fetch(request)
          .then((response) => {
            if (response.ok || response.type === 'opaque') cache.put(request, response.clone());
            return response;
          })
          .catch(() => hit);
        return hit ?? network;
      }),
    );
    return;
  }

  if (new URL(url).origin !== self.location.origin) return;

  // A navigation must resolve to the app shell so a deep link works offline.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(async () => {
        const cache = await caches.open(CACHE);
        return (
          (await cache.match('./', MATCH)) ??
          (await cache.match('./index.html', MATCH)) ??
          Response.error()
        );
      }),
    );
    return;
  }

  // Everything else in the shell is content-hashed, so cache-first is safe.
  event.respondWith(
    caches.match(request, MATCH).then(
      (hit) =>
        hit ??
        fetch(request).then((response) => {
          if (response.ok) {
            const copy = response.clone();
            void caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        }),
    ),
  );
});
`;

writeFileSync(join(DIST, 'sw.js'), sw);
console.log(`${DIST}/sw.js — cache dodge-asteroid-${version}, ${precache.length} entries`);
